Add available query string params to order path and query functions
MorpheusNephew/td-ameritrade pull request #35
Opened 2021-11-28 16:47 UTC by jdgriffith

This PR allows clients to query by more attributes made available by TD Ameritrade.

2021-11-28 17:15 UTC, jdgriffith commented
@MorpheusNephew Let me know if you need me to do anything different to get this merged.

2021-11-28 17:16 UTC, jdgriffith commented on src/clients/orders-client.ts
> +  fromEnteredTime: Date;
Could possibly have this be `Date | string'.

2021-11-28 18:33 UTC, MorpheusNephew commented on src/clients/orders-client.ts
> +  fromEnteredTime: Date;
I'll take a look at the docs and see

2021-11-28 18:46 UTC, MorpheusNephew requested changes
Left a comment about the status property. Also, if you don't mind could you change the time/date properties to be `Date | string`?

2021-11-28 18:46 UTC, MorpheusNephew commented on src/clients/orders-client.ts
> +  status: Array<OrderStatus>;
Based on the docs for [get orders by query](https://developer.tdameritrade.com/account-access/apis/get/orders-0) and [get orders by path](https://developer.tdameritrade.com/account-access/apis/get/accounts/%7BaccountId%7D/orders-0) it appears that this (status) isn't an array, but status would just be `OrderStatus`

2021-11-28 20:17 UTC, jdgriffith commented on src/clients/orders-client.ts
> +  status: Array<OrderStatus>;
I'm curious about this because only sending one status would be limiting. If it _does_ allow for more than one status I wonder if it expects it as a comma-separated value or the query param array standard. 

I will see if I can't test this with the API for a better idea.

2021-11-28 20:32 UTC, jdgriffith commented on src/clients/orders-client.ts
> +  fromEnteredTime: Date;
Final format should be `yyyy-MM-dd`.

2021-11-28 20:35 UTC, MorpheusNephew commented on src/clients/orders-client.ts
> +  status: Array<OrderStatus>;
Correct, each status would be limiting. If there's no status value then all order statuses will return, so this and the other properties should probably optional since they aren't required to make the request

2021-11-28 20:41 UTC, jdgriffith commented on src/clients/orders-client.ts
> +  status: Array<OrderStatus>;
<img width="1156" alt="Screen Shot 2021-11-28 at 2 39 20 PM" src="https://user-images.githubusercontent.com/872496/143785144-d74da624-d01c-4ca3-8166-6b1512230c7f.png">

Good catch. Multiple statuses for this API "query" doesn't work. A little unfortunate, but easy to work around.

2021-11-28 23:12 UTC, jdgriffith commented on src/clients/orders-client.ts
> +  fromEnteredTime: Date;
Updated.

2021-11-28 23:13 UTC, jdgriffith commented on src/clients/orders-client.ts
> +  status: Array<OrderStatus>;
Updated to merely take in one `OrderStatus`.

2021-11-28 23:13 UTC, jdgriffith commented on src/clients/orders-client.ts
> +  status: Array<OrderStatus>;
I also made it to where the new properties are optional.

2021-11-28 23:15 UTC, jdgriffith commented on src/clients/orders-client.ts
> +    if (options?.fromEnteredTime && options.fromEnteredTime instanceof Date) {
Let me know if you are ok with adding params logic here. I know sometimes this stuff can quickly start to get out of hand but wanted to add something to format the date before it gets pushed across the wire.

2021-11-29 00:04 UTC, MorpheusNephew commented on src/clients/orders-client.ts
> +    if (options?.fromEnteredTime && options.fromEnteredTime instanceof Date) {
Yeah, I'm not sure about the params logic. My vision for this project is to just be somewhat of a passthrough to the TD's underlying API. I don't want it to be opinionated in any way. So if a request fails or something blows up, I want it to be because a user didn't provide the necessary data to TD's API instead of it not conforming to something this client requires in any way.

2021-12-04 14:38 UTC, jdgriffith commented on src/clients/orders-client.ts
> +    if (options?.fromEnteredTime && options.fromEnteredTime instanceof Date) {
Got it. Will update according.

2021-12-04 14:42 UTC, jdgriffith commented on src/clients/orders-client.ts
> +    if (options?.fromEnteredTime && options.fromEnteredTime instanceof Date) {
Updated. Very small code change at this point. Let me know if anything else further needs to be done.

2021-12-04 14:44 UTC, jdgriffith commented on src/clients/orders-client.ts
> +  fromEnteredTime?: string;
Keeping this as string only since it needs to fit a specific format.

2021-12-04 15:44 UTC, jdgriffith commented on src/clients/orders-client.ts
> +  fromEnteredTime?: string;
I missed/forgot about your one comment related to `Date | string`. I think a date object will be default fail against the API if not formatters. Do you still want that?

2021-12-05 05:20 UTC, MorpheusNephew commented on src/clients/orders-client.ts
> +  fromEnteredTime?: string;
Gotcha, not a problem you can leave it as a string

2021-12-06 16:03 UTC, MorpheusNephew approved these changes

2021-12-07 12:08 UTC, merged